# Site settings
title: "Kostas Siabanis"
email: "kostas.siabanis@gmail.com"
description: "Full-stack web developer, JavaScript enthusiast, IT expert"
baseurl: ""
url: "http://kostassiabanis.com/"
title_description: "By day, I am an IT expert (12+ years) working with databases (sql or not), gathering and reporting on data and customising ERP systems. I am also a passionate self taught full-stack developer (5+ years) that worked on several projects using PHP and MySQL and now focusing exclusively on JavaScript both on the client and the server."
title_image: "https://avatars1.githubusercontent.com/u/3550488?v=3&s=460"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: "https://github.com/ksiabani"
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: ksiabani
github_username:  ksiabani
linkedin_link: https://gr.linkedin.com/in/ksiabani
google_plus_link: https://plus.google.com/+KostasSiabanis
stackoverflow_link: http://stackoverflow.com/users/4964370/kostas-siabanis

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_left: "<a href="http://brianmaierjr.com">Brian Maier Jr.</a> Powered by <a href="http://jekyllrb.com">Jekyll</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
#markdown: redcarpet
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
#highlighter: rouge
